### ISSUE TITLE
error: 'PPPoS' does not name a type

### ISSUE THREAD

**Issue by dhsont** [vshymanskyy/ESP32_PPPoS#3]
I am getting following error while using example

```
src\main.cpp:12:1: error: 'PPPoS' does not name a type
 PPPoS ppp;
 ^
src\main.cpp: In function 'void setup()':
src\main.cpp:24:3: error: 'ppp' was not declared in this scope
   ppp.begin(&Serial1);
```

**Comment by dhsont** [comment]
working with esp version 2.0

but http response code is -1   for requests
